### ISSUE TITLE
Port from non-sdk-style to sdk-style project: Access custom static class properties

### ISSUE THREAD

**Issue by pulla2908** [devlooped/GitInfo#141]
We are using GitInfo in `.NET Framework 4.7.2` non-sdk-style projects so far. In `C#` we have defined a static class (`VersionInfo`) which calculates relevant information for the assembly versioning based on properties from `ThisAssembly`.

This is `VersionInfo`:
````
public static class VersionInfo
{
    public const string AssemblyVersion = <custom code here>;
    public const string AssemblyFileVersion = <custom code here>;
    public const string AssemblyInformationalVersion = <custom code here>;
}
````
This is the usage in non-sdk-style projects:
````
[assembly: AssemblyVersion(VersionInfo.AssemblyVersion)]
[assembly: AssemblyFileVersion(VersionInfo.AssemblyFileVersion)]
[assembly: AssemblyInformationalVersion(VersionInfo.AssemblyInformationalVersion)]
````
Now we have ported some class library projects to `.NET Standard 2.0` with sdk-style project. As far I understood the versioning can not be done in the same way as it was done for non-sdk-style projects. Instead I think I have to do attach to the build target like that:
````
<ItemGroup>
    <PackageReference Include="GitInfo" Version="2.1.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>   
</ItemGroup>
<Target Name="SetAssemblyInfoVersions" AfterTargets="PrepareForBuild" BeforeTargets="GenerateAssemblyInfo" DependsOnTargets="GitVersion">
    <PropertyGroup>
        <FileVersion>$([VersionInfo]::AssemblyVersion.ToString())</FileVersion>      
    </PropertyGroup>
</Target>
````
Here I try to invoke my static class properties. But as it seems that might not be possible to do that for any type. According to [to](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019) only a few types can be used.

Question: Any idea how to solve that for sdk-style projects?

**Comment by kzu** [comment]
I may be wrong, but I doubt very much that you can invoke that `VersionInfo` from a custom type of yours in non-SDK-style either.

You should be doing it the other way around... MSBuild is the one that calculates the versions, not your code. Your code just provides constants so your *code* (not your build scripts) know and do something with that. Otherwise, you have a chicken-egg situation.

**Comment by pulla2908** [comment]
@kzu I thought that already. It is a legacy project and I don't know why people decided to calculate something in the code. I will take a further look on it and I think one day I have to rework it.

**Comment by kzu** [comment]
My point is that I very much doubt that that is working at all presently. MSBuild doesn't care about legacy or SDK-style. You're invoking a custom type that's not been compiled yet.

I'm tentatively closing this since this is pure MSBuild, not related to this project. Plz feel free to reopen if there's anything else we can suggest.

**Comment by pulla2908** [comment]
@kzu fine for me! If I have some update I can post it here.
