### ISSUE TITLE
Should `$(GitDefaultBranch)` now default to `main` rather than `master`

### ISSUE THREAD

**Issue by dellis1972** [devlooped/GitInfo#167]
GitHub has changed its default branch from `master` to `main`.
Should `GitDefaultBranch` be updated to match?

**Comment by kzu** [comment]
Perhaps. It would be a breaking change for folks and for branch commit count from fork point (if the branch remains 'master'), so perhaps this should go with a notice and a major version change?

**Comment by dellis1972** [comment]
Or issue a warning now, and then change in a few months along with a major version change?

@kzu hope you are doing well btw :D

**Comment by dellis1972** [comment]
I can make the required changes for the warning if you like and do a PR.

**Comment by kzu** [comment]
Hey @dellis1972! Thanks for dropping by 🤟 . 

So perhaps the logic for the warning would be: you don't have a `GitDefaultBranch` property set (meaning next major will break you). Should we warn/info if you have it set to `main`, saying it won't be necessary down the road? Or no warning at all in that case? (I kinda dislike it when projects duplicate values that equal their defaults, since that's just clutter).
