### ISSUE TITLE
Privacy about SponsorLink with GitInfo

### ISSUE THREAD

**Issue by masterminh219** [devlooped/GitInfo#299]
## Describe the Bug

Since I'm using GitInfo and I'm aware that Moq privacy has been raised at: https://github.com/moq/moq/issues/1372, 

Can we confirm that GitInfo does not affect or not? (I found that there is a dependency with SponsorLink)

**Comment by GerardSmit** [comment]
GitInfo is also effected, since it has a dependency to SponsorLink.

Since v3.0.0-alpha SponsorLink was added to this repository: https://github.com/devlooped/GitInfo/pull/217
Even worse, GitInfo v3.0.1 till v3.1.2 used to validate if you're a sponsor with your email address instead of the hash (https://github.com/devlooped/SponsorLink/blob/main/releases.md#whats-changed-11).

If you're using a version earlier than v3.0.0 you're not affected.

**Comment by BinToss** [comment]
SponsorLink is also a dependency of `ThisAssembly.Constants` which GitInfo relies on.

**Comment by NiKiZe** [comment]
SponsorLink is malware, any package that uses SponsorLink will be flagged as such as well.

**Comment by rakenodiax** [comment]
GitInfo is in the same org as SpysorLink, so I doubt it'll be removed

**Comment by kzu** [comment]
Dependency gone for a while now.
